2024-08-25 13:18:19,006 - app_logger - ERROR - HTTPException: the JSON object must be str, bytes or bytearray, not list (status: {'ret_code': -1, 'ret_txt': 'the JSON object must be str, bytes or bytearray, not list'})
2024-08-25 13:18:54,528 - app_logger - INFO - Inicio de la ejecución
2024-08-25 13:18:54,907 - uvicorn.error - INFO - Started server process [21244]
2024-08-25 13:18:54,908 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 13:18:54,908 - uvicorn.error - INFO - Application startup complete.
2024-08-25 13:18:57,276 - app_logger - ERROR - HTTPException: {'ret_code': -3, 'ret_txt': 'the JSON object must be str, bytes or bytearray, not list'} (status: {'ret_code': -1, 'ret_txt': "{'ret_code': -3, 'ret_txt': 'the JSON object must be str, bytes or bytearray, not list'}"})
2024-08-25 13:19:27,450 - app_logger - INFO - Inicio de la ejecución
2024-08-25 13:19:28,266 - app_logger - INFO - Inicio de la ejecución
2024-08-25 13:19:28,313 - uvicorn.error - INFO - Started server process [22724]
2024-08-25 13:19:28,313 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 13:19:28,314 - uvicorn.error - INFO - Application startup complete.
2024-08-25 13:19:29,453 - app_logger - ERROR - HTTPException: {'ret_code': -3, 'ret_txt': 'the JSON object must be str, bytes or bytearray, not list'} (status: {'ret_code': -1, 'ret_txt': "{'ret_code': -3, 'ret_txt': 'the JSON object must be str, bytes or bytearray, not list'}"})
2024-08-25 13:21:33,855 - app_logger - INFO - Inicio de la ejecución
2024-08-25 13:21:33,900 - uvicorn.error - INFO - Started server process [27848]
2024-08-25 13:21:33,901 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 13:21:33,902 - uvicorn.error - INFO - Application startup complete.
2024-08-25 13:21:34,450 - app_logger - INFO - Inicio de la ejecución
2024-08-25 13:21:34,494 - uvicorn.error - INFO - Started server process [37444]
2024-08-25 13:21:34,494 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 13:21:34,495 - uvicorn.error - INFO - Application startup complete.
2024-08-25 13:21:35,528 - app_logger - ERROR - HTTPException: {'ret_code': -3, 'ret_txt': 'the JSON object must be str, bytes or bytearray, not list'} (status: {'ret_code': -1, 'ret_txt': "{'ret_code': -3, 'ret_txt': 'the JSON object must be str, bytes or bytearray, not list'}"})
2024-08-25 13:22:21,302 - app_logger - INFO - Inicio de la ejecución
2024-08-25 13:22:21,347 - uvicorn.error - INFO - Started server process [23028]
2024-08-25 13:22:21,347 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 13:22:21,348 - uvicorn.error - INFO - Application startup complete.
2024-08-25 13:22:22,251 - app_logger - ERROR - HTTPException: {'ret_code': -3, 'ret_txt': 'the JSON object must be str, bytes or bytearray, not list'} (status: {'ret_code': -1, 'ret_txt': "{'ret_code': -3, 'ret_txt': 'the JSON object must be str, bytes or bytearray, not list'}"})
2024-08-25 13:23:17,769 - app_logger - INFO - Inicio de la ejecución
2024-08-25 13:23:17,815 - uvicorn.error - INFO - Started server process [16552]
2024-08-25 13:23:17,815 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 13:23:17,816 - uvicorn.error - INFO - Application startup complete.
2024-08-25 13:23:18,814 - app_logger - ERROR - HTTPException: {'ret_code': -3, 'ret_txt': 'the JSON object must be str, bytes or bytearray, not list'} (status: {'ret_code': -1, 'ret_txt': "{'ret_code': -3, 'ret_txt': 'the JSON object must be str, bytes or bytearray, not list'}"})
2024-08-25 13:23:53,039 - app_logger - INFO - Inicio de la ejecución
2024-08-25 13:23:53,083 - uvicorn.error - INFO - Started server process [12092]
2024-08-25 13:23:53,084 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 13:23:53,084 - uvicorn.error - INFO - Application startup complete.
2024-08-25 13:23:55,060 - app_logger - ERROR - HTTPException: unhashable type: 'dict' (status: {'ret_code': -1, 'ret_txt': "unhashable type: 'dict'"})
2024-08-25 13:24:53,459 - app_logger - INFO - Inicio de la ejecución
2024-08-25 13:24:53,503 - uvicorn.error - INFO - Started server process [38952]
2024-08-25 13:24:53,503 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 13:24:53,503 - uvicorn.error - INFO - Application startup complete.
2024-08-25 13:24:53,993 - app_logger - INFO - Inicio de la ejecución
2024-08-25 13:24:54,039 - uvicorn.error - INFO - Started server process [19348]
2024-08-25 13:24:54,040 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 13:24:54,040 - uvicorn.error - INFO - Application startup complete.
2024-08-25 13:24:56,581 - app_logger - ERROR - HTTPException: unhashable type: 'dict' (status: {'ret_code': -1, 'ret_txt': "unhashable type: 'dict'"})
2024-08-25 13:25:44,081 - app_logger - INFO - Inicio de la ejecución
2024-08-25 13:25:44,131 - uvicorn.error - INFO - Started server process [12300]
2024-08-25 13:25:44,131 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 13:25:44,132 - uvicorn.error - INFO - Application startup complete.
2024-08-25 13:25:45,497 - app_logger - ERROR - HTTPException: {'ret_code': -3, 'ret_txt': 'the JSON object must be str, bytes or bytearray, not list'} (status: {'ret_code': -1, 'ret_txt': "{'ret_code': -3, 'ret_txt': 'the JSON object must be str, bytes or bytearray, not list'}"})
2024-08-25 13:26:03,139 - app_logger - INFO - Inicio de la ejecución
2024-08-25 13:26:03,184 - uvicorn.error - INFO - Started server process [38984]
2024-08-25 13:26:03,184 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 13:26:03,185 - uvicorn.error - INFO - Application startup complete.
2024-08-25 13:26:05,476 - app_logger - ERROR - HTTPException: the JSON object must be str, bytes or bytearray, not list (status: {'ret_code': -1, 'ret_txt': 'the JSON object must be str, bytes or bytearray, not list'})
2024-08-25 13:26:52,447 - app_logger - INFO - Inicio de la ejecución
2024-08-25 13:26:52,945 - uvicorn.error - INFO - Started server process [688]
2024-08-25 13:26:52,945 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 13:26:52,946 - uvicorn.error - INFO - Application startup complete.
2024-08-25 13:27:54,391 - app_logger - INFO - Inicio de la ejecución
2024-08-25 13:27:54,703 - uvicorn.error - INFO - Started server process [37248]
2024-08-25 13:27:54,703 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 13:27:54,704 - uvicorn.error - INFO - Application startup complete.
2024-08-25 13:28:38,146 - app_logger - INFO - Inicio de la ejecución
2024-08-25 13:28:38,614 - uvicorn.error - INFO - Started server process [25932]
2024-08-25 13:28:38,614 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 13:28:38,614 - uvicorn.error - INFO - Application startup complete.
2024-08-25 13:28:51,099 - app_logger - INFO - Inicio de la ejecución
2024-08-25 13:28:51,145 - uvicorn.error - INFO - Started server process [18380]
2024-08-25 13:28:51,145 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 13:28:51,146 - uvicorn.error - INFO - Application startup complete.
2024-08-25 13:29:23,542 - app_logger - INFO - Inicio de la ejecución
2024-08-25 13:29:23,584 - uvicorn.error - INFO - Started server process [39240]
2024-08-25 13:29:23,585 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 13:29:23,585 - uvicorn.error - INFO - Application startup complete.
2024-08-25 13:30:33,531 - app_logger - INFO - Inicio de la ejecución
2024-08-25 13:30:33,949 - uvicorn.error - INFO - Started server process [28020]
2024-08-25 13:30:33,950 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 13:30:33,950 - uvicorn.error - INFO - Application startup complete.
2024-08-25 13:30:36,829 - app_logger - ERROR - Unhandled Exception: MadreException.__init__() got an unexpected keyword argument 'status_code'
2024-08-25 13:30:36,830 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "D:\Nube\GitHub\Madre_API\app\api\routes\semillas.py", line 77, in lista_centros
    raise MadreException(resultado, 400)
app.utils.mis_excepciones.MadreException: the JSON object must be str, bytes or bytearray, not list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\exceptions.py", line 93, in __call__
    raise exc
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Nube\GitHub\Madre_API\app\api\routes\semillas.py", line 84, in lista_centros
    raise MadreException(status_code=400, detail=e)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MadreException.__init__() got an unexpected keyword argument 'status_code'
2024-08-25 13:32:27,994 - app_logger - INFO - Inicio de la ejecución
2024-08-25 13:32:28,040 - uvicorn.error - INFO - Started server process [22248]
2024-08-25 13:32:28,040 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 13:32:28,041 - uvicorn.error - INFO - Application startup complete.
2024-08-25 13:32:30,586 - app_logger - ERROR - Unhandled Exception: MadreException.__init__() got an unexpected keyword argument 'detail'
2024-08-25 13:32:30,587 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "D:\Nube\GitHub\Madre_API\app\api\routes\semillas.py", line 77, in lista_centros
    raise MadreException(resultado, 400)
app.utils.mis_excepciones.MadreException: the JSON object must be str, bytes or bytearray, not list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\exceptions.py", line 93, in __call__
    raise exc
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Nube\GitHub\Madre_API\app\api\routes\semillas.py", line 84, in lista_centros
    raise MadreException(status_code=400, detail=e)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MadreException.__init__() got an unexpected keyword argument 'detail'
2024-08-25 13:33:16,706 - app_logger - INFO - Inicio de la ejecución
2024-08-25 13:33:16,750 - uvicorn.error - INFO - Started server process [23492]
2024-08-25 13:33:16,751 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 13:33:16,751 - uvicorn.error - INFO - Application startup complete.
2024-08-25 13:33:17,344 - app_logger - INFO - Inicio de la ejecución
2024-08-25 13:33:17,390 - uvicorn.error - INFO - Started server process [37356]
2024-08-25 13:33:17,391 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 13:33:17,391 - uvicorn.error - INFO - Application startup complete.
2024-08-25 13:33:18,195 - app_logger - ERROR - Unhandled Exception: 'MadreException' object has no attribute 'ret_code'
2024-08-25 13:33:18,196 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "D:\Nube\GitHub\Madre_API\app\api\routes\semillas.py", line 77, in lista_centros
    raise MadreException(resultado, 400)
app.utils.mis_excepciones.MadreException: the JSON object must be str, bytes or bytearray, not list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Nube\GitHub\Madre_API\app\api\routes\semillas.py", line 84, in lista_centros
    raise MadreException(status_code=400, detail=e)
app.utils.mis_excepciones.MadreException: the JSON object must be str, bytes or bytearray, not list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\exceptions.py", line 101, in __call__
    response = await handler(request, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Nube\GitHub\Madre_API\app\exceptions.py", line 54, in madre_exception_handler
    logger.error(f"MadreException: (status: {exc.ret_code} {exc.ret_txt})")
                                             ^^^^^^^^^^^^
AttributeError: 'MadreException' object has no attribute 'ret_code'
2024-08-25 13:34:09,528 - app_logger - INFO - Inicio de la ejecución
2024-08-25 13:34:09,573 - uvicorn.error - INFO - Started server process [34944]
2024-08-25 13:34:09,573 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 13:34:09,574 - uvicorn.error - INFO - Application startup complete.
2024-08-25 13:34:10,739 - app_logger - ERROR - Unhandled Exception: 'MadreException' object has no attribute 'detail'
2024-08-25 13:34:10,740 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "D:\Nube\GitHub\Madre_API\app\api\routes\semillas.py", line 77, in lista_centros
    raise MadreException(resultado, 400)
app.utils.mis_excepciones.MadreException: the JSON object must be str, bytes or bytearray, not list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Nube\GitHub\Madre_API\app\api\routes\semillas.py", line 84, in lista_centros
    raise MadreException(status_code=400, detail=e)
app.utils.mis_excepciones.MadreException: the JSON object must be str, bytes or bytearray, not list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\exceptions.py", line 101, in __call__
    response = await handler(request, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Nube\GitHub\Madre_API\app\exceptions.py", line 54, in madre_exception_handler
    logger.error(f"MadreException: (status: {exc.status_code} {exc.detail})")
                                                               ^^^^^^^^^^
AttributeError: 'MadreException' object has no attribute 'detail'
2024-08-25 13:34:33,421 - app_logger - INFO - Inicio de la ejecución
2024-08-25 13:34:33,467 - uvicorn.error - INFO - Started server process [32440]
2024-08-25 13:34:33,467 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 13:34:33,468 - uvicorn.error - INFO - Application startup complete.
2024-08-25 13:34:35,170 - app_logger - ERROR - MadreException: (status: 400 {'ret_code': -1, 'ret_txt': MadreException('the JSON object must be str, bytes or bytearray, not list')})
2024-08-25 13:34:35,171 - app_logger - ERROR - Unhandled Exception: 'MadreException' object has no attribute 'ret_txt'
2024-08-25 13:34:35,171 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "D:\Nube\GitHub\Madre_API\app\api\routes\semillas.py", line 77, in lista_centros
    raise MadreException(resultado, 400)
app.utils.mis_excepciones.MadreException: the JSON object must be str, bytes or bytearray, not list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Nube\GitHub\Madre_API\app\api\routes\semillas.py", line 84, in lista_centros
    raise MadreException(status_code=400, detail=e)
app.utils.mis_excepciones.MadreException: the JSON object must be str, bytes or bytearray, not list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\exceptions.py", line 101, in __call__
    response = await handler(request, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Nube\GitHub\Madre_API\app\exceptions.py", line 56, in madre_exception_handler
    if isinstance(exc.ret_txt, dict):
                  ^^^^^^^^^^^
AttributeError: 'MadreException' object has no attribute 'ret_txt'
2024-08-25 13:35:35,501 - app_logger - INFO - Inicio de la ejecución
2024-08-25 13:35:35,547 - uvicorn.error - INFO - Started server process [10148]
2024-08-25 13:35:35,547 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 13:35:35,548 - uvicorn.error - INFO - Application startup complete.
2024-08-25 13:35:37,242 - app_logger - ERROR - MadreException: (status: 400 {'ret_code': -1, 'ret_txt': MadreException('the JSON object must be str, bytes or bytearray, not list')})
2024-08-25 13:35:37,242 - app_logger - ERROR - Unhandled Exception: Object of type MadreException is not JSON serializable
2024-08-25 13:35:37,243 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "D:\Nube\GitHub\Madre_API\app\api\routes\semillas.py", line 77, in lista_centros
    raise MadreException(resultado, 400)
app.utils.mis_excepciones.MadreException: the JSON object must be str, bytes or bytearray, not list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Nube\GitHub\Madre_API\app\api\routes\semillas.py", line 84, in lista_centros
    raise MadreException(status_code=400, detail=e)
app.utils.mis_excepciones.MadreException: the JSON object must be str, bytes or bytearray, not list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\exceptions.py", line 101, in __call__
    response = await handler(request, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Nube\GitHub\Madre_API\app\exceptions.py", line 64, in madre_exception_handler
    return JSONResponse(
           ^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\responses.py", line 187, in __init__
    super().__init__(content, status_code, headers, media_type, background)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\responses.py", line 49, in __init__
    self.body = self.render(content)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\responses.py", line 190, in render
    return json.dumps(
           ^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type MadreException is not JSON serializable
2024-08-25 13:37:14,434 - app_logger - INFO - Inicio de la ejecución
2024-08-25 13:37:14,845 - uvicorn.error - INFO - Started server process [27820]
2024-08-25 13:37:14,845 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 13:37:14,846 - uvicorn.error - INFO - Application startup complete.
2024-08-25 13:37:30,987 - app_logger - ERROR - MadreException: (status: 400 {'ret_code': -1, 'ret_txt': MadreException('the JSON object must be str, bytes or bytearray, not list')})
2024-08-25 13:37:30,987 - app_logger - ERROR - Unhandled Exception: Object of type MadreException is not JSON serializable
2024-08-25 13:37:30,987 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "D:\Nube\GitHub\Madre_API\app\api\routes\semillas.py", line 77, in lista_centros
    raise MadreException(resultado, 400)
app.utils.mis_excepciones.MadreException: the JSON object must be str, bytes or bytearray, not list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Nube\GitHub\Madre_API\app\api\routes\semillas.py", line 84, in lista_centros
    raise MadreException(status_code=400, detail=e)
app.utils.mis_excepciones.MadreException: the JSON object must be str, bytes or bytearray, not list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\exceptions.py", line 101, in __call__
    response = await handler(request, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Nube\GitHub\Madre_API\app\exceptions.py", line 64, in madre_exception_handler
    return JSONResponse(
           ^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\responses.py", line 187, in __init__
    super().__init__(content, status_code, headers, media_type, background)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\responses.py", line 49, in __init__
    self.body = self.render(content)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\responses.py", line 190, in render
    return json.dumps(
           ^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type MadreException is not JSON serializable
2024-08-25 13:39:21,393 - app_logger - INFO - Inicio de la ejecución
2024-08-25 13:39:21,940 - uvicorn.error - INFO - Started server process [23464]
2024-08-25 13:39:21,940 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 13:39:21,940 - uvicorn.error - INFO - Application startup complete.
2024-08-25 13:39:25,491 - app_logger - ERROR - MadreException: (status: 400 {'ret_code': -1, 'ret_txt': MadreException('the JSON object must be str, bytes or bytearray, not list')})
2024-08-25 13:39:25,491 - app_logger - ERROR - Unhandled Exception: Object of type MadreException is not JSON serializable
2024-08-25 13:39:25,492 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "D:\Nube\GitHub\Madre_API\app\api\routes\semillas.py", line 77, in lista_centros
    raise MadreException({"ret_code": resultado['ret_code'],"ret_txt": resultado['ret_txt']}, 400)
app.utils.mis_excepciones.MadreException: the JSON object must be str, bytes or bytearray, not list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Nube\GitHub\Madre_API\app\api\routes\semillas.py", line 84, in lista_centros
    raise MadreException(status_code=400, detail=e)
app.utils.mis_excepciones.MadreException: the JSON object must be str, bytes or bytearray, not list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\exceptions.py", line 101, in __call__
    response = await handler(request, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Nube\GitHub\Madre_API\app\exceptions.py", line 64, in madre_exception_handler
    return JSONResponse(
           ^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\responses.py", line 187, in __init__
    super().__init__(content, status_code, headers, media_type, background)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\responses.py", line 49, in __init__
    self.body = self.render(content)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\responses.py", line 190, in render
    return json.dumps(
           ^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type MadreException is not JSON serializable
2024-08-25 20:44:42,741 - app_logger - ERROR - MadreException: (status: 400 {'ret_code': -1, 'ret_txt': MadreException('the JSON object must be str, bytes or bytearray, not list')})
2024-08-25 20:44:42,742 - app_logger - ERROR - Unhandled Exception: Object of type MadreException is not JSON serializable
2024-08-25 20:44:42,742 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "D:\Nube\GitHub\Madre_API\app\api\routes\semillas.py", line 77, in lista_centros
    raise MadreException({"ret_code": resultado['ret_code'],"ret_txt": resultado['ret_txt']}, 400)
app.utils.mis_excepciones.MadreException: the JSON object must be str, bytes or bytearray, not list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Nube\GitHub\Madre_API\app\api\routes\semillas.py", line 84, in lista_centros
    raise MadreException(status_code=400, detail=e)
app.utils.mis_excepciones.MadreException: the JSON object must be str, bytes or bytearray, not list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\exceptions.py", line 101, in __call__
    response = await handler(request, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Nube\GitHub\Madre_API\app\exceptions.py", line 64, in madre_exception_handler
    return JSONResponse(
           ^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\responses.py", line 187, in __init__
    super().__init__(content, status_code, headers, media_type, background)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\responses.py", line 49, in __init__
    self.body = self.render(content)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\responses.py", line 190, in render
    return json.dumps(
           ^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type MadreException is not JSON serializable
2024-08-25 20:47:46,319 - app_logger - INFO - Inicio de la ejecución
2024-08-25 20:47:46,370 - uvicorn.error - INFO - Started server process [26772]
2024-08-25 20:47:46,370 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 20:47:46,371 - uvicorn.error - INFO - Application startup complete.
2024-08-25 20:47:49,706 - app_logger - ERROR - MadreException: (status: 400 {'ret_code': -1, 'ret_txt': MadreException('the JSON object must be str, bytes or bytearray, not list')})
2024-08-25 20:47:49,706 - app_logger - ERROR - Unhandled Exception: Object of type MadreException is not JSON serializable
2024-08-25 20:47:49,707 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "D:\Nube\GitHub\Madre_API\app\api\routes\semillas.py", line 77, in lista_centros
    raise MadreException({"ret_code": resultado['ret_code'],"ret_txt": resultado['ret_txt']}, 400)
app.utils.mis_excepciones.MadreException: the JSON object must be str, bytes or bytearray, not list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Nube\GitHub\Madre_API\app\api\routes\semillas.py", line 84, in lista_centros
    raise MadreException(status_code=400, detail=e)
app.utils.mis_excepciones.MadreException: the JSON object must be str, bytes or bytearray, not list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\exceptions.py", line 101, in __call__
    response = await handler(request, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Nube\GitHub\Madre_API\app\exceptions.py", line 64, in madre_exception_handler
    return JSONResponse(
           ^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\responses.py", line 187, in __init__
    super().__init__(content, status_code, headers, media_type, background)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\responses.py", line 49, in __init__
    self.body = self.render(content)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\responses.py", line 190, in render
    return json.dumps(
           ^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type MadreException is not JSON serializable
2024-08-25 20:57:36,636 - app_logger - INFO - Inicio de la ejecución
2024-08-25 20:57:36,679 - uvicorn.error - INFO - Started server process [10232]
2024-08-25 20:57:36,680 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 20:57:36,680 - uvicorn.error - INFO - Application startup complete.
2024-08-25 20:57:42,300 - app_logger - ERROR - MadreException: (status: 400 {'ret_code': -1, 'ret_txt': MadreException('the JSON object must be str, bytes or bytearray, not list')})
2024-08-25 20:57:42,300 - app_logger - ERROR - Unhandled Exception: Object of type MadreException is not JSON serializable
2024-08-25 20:57:42,301 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "D:\Nube\GitHub\Madre_API\app\api\routes\semillas.py", line 77, in lista_centros
    raise MadreException({"ret_code": resultado['ret_code'],"ret_txt": resultado['ret_txt']}, 400)
app.utils.mis_excepciones.MadreException: the JSON object must be str, bytes or bytearray, not list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Nube\GitHub\Madre_API\app\api\routes\semillas.py", line 84, in lista_centros
    raise MadreException(status_code=400, detail=e)
app.utils.mis_excepciones.MadreException: the JSON object must be str, bytes or bytearray, not list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\exceptions.py", line 101, in __call__
    response = await handler(request, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Nube\GitHub\Madre_API\app\exceptions.py", line 64, in madre_exception_handler
    return JSONResponse(
           ^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\responses.py", line 187, in __init__
    super().__init__(content, status_code, headers, media_type, background)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\responses.py", line 49, in __init__
    self.body = self.render(content)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\responses.py", line 190, in render
    return json.dumps(
           ^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type MadreException is not JSON serializable
2024-08-25 20:57:57,170 - uvicorn.error - INFO - Shutting down
2024-08-25 20:57:57,278 - uvicorn.error - INFO - Waiting for application shutdown.
2024-08-25 20:57:57,278 - uvicorn.error - INFO - Application shutdown complete.
2024-08-25 20:57:57,278 - uvicorn.error - INFO - Finished server process [10232]
2024-08-25 20:58:02,362 - app_logger - INFO - Inicio de la ejecución
2024-08-25 20:58:02,404 - uvicorn.error - INFO - Started server process [11832]
2024-08-25 20:58:02,404 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 20:58:02,405 - uvicorn.error - INFO - Application startup complete.
2024-08-25 20:58:05,756 - app_logger - ERROR - MadreException: (status: 400 {'ret_code': -1, 'ret_txt': MadreException('the JSON object must be str, bytes or bytearray, not list')})
2024-08-25 20:58:05,757 - app_logger - ERROR - Unhandled Exception: Object of type MadreException is not JSON serializable
2024-08-25 20:58:05,757 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "D:\Nube\GitHub\Madre_API\app\api\routes\semillas.py", line 77, in lista_centros
    raise MadreException({"ret_code": resultado['ret_code'],"ret_txt": resultado['ret_txt']}, 400)
app.utils.mis_excepciones.MadreException: the JSON object must be str, bytes or bytearray, not list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Nube\GitHub\Madre_API\app\api\routes\semillas.py", line 84, in lista_centros
    raise MadreException(status_code=400, detail=e)
app.utils.mis_excepciones.MadreException: the JSON object must be str, bytes or bytearray, not list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\exceptions.py", line 101, in __call__
    response = await handler(request, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Nube\GitHub\Madre_API\app\exceptions.py", line 64, in madre_exception_handler
    return JSONResponse(
           ^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\responses.py", line 187, in __init__
    super().__init__(content, status_code, headers, media_type, background)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\responses.py", line 49, in __init__
    self.body = self.render(content)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\responses.py", line 190, in render
    return json.dumps(
           ^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type MadreException is not JSON serializable
2024-08-25 21:04:44,921 - app_logger - INFO - Inicio de la ejecución
2024-08-25 21:04:44,966 - uvicorn.error - INFO - Started server process [17384]
2024-08-25 21:04:44,967 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 21:04:44,967 - uvicorn.error - INFO - Application startup complete.
2024-08-25 21:05:58,905 - app_logger - INFO - Inicio de la ejecución
2024-08-25 21:05:59,234 - uvicorn.error - INFO - Started server process [10512]
2024-08-25 21:05:59,235 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 21:05:59,235 - uvicorn.error - INFO - Application startup complete.
2024-08-25 21:06:00,306 - app_logger - ERROR - HTTPException: the JSON object must be str, bytes or bytearray, not list (status: {'ret_code': -1, 'ret_txt': 'the JSON object must be str, bytes or bytearray, not list'})
2024-08-25 21:07:03,503 - app_logger - INFO - Inicio de la ejecución
2024-08-25 21:07:03,551 - uvicorn.error - INFO - Started server process [25088]
2024-08-25 21:07:03,552 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 21:07:03,552 - uvicorn.error - INFO - Application startup complete.
2024-08-25 21:07:24,323 - uvicorn.error - INFO - Shutting down
2024-08-25 21:07:27,718 - app_logger - INFO - Inicio de la ejecución
2024-08-25 21:07:27,763 - uvicorn.error - INFO - Started server process [14892]
2024-08-25 21:07:27,763 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 21:07:27,764 - uvicorn.error - INFO - Application startup complete.
2024-08-25 21:07:30,010 - app_logger - ERROR - HTTPException: ({'ret_code': -3, 'ret_txt': 'the JSON object must be str, bytes or bytearray, not list'}, 400) (status: {'ret_code': -1, 'ret_txt': "({'ret_code': -3, 'ret_txt': 'the JSON object must be str, bytes or bytearray, not list'}, 400)"})
2024-08-25 21:10:38,142 - app_logger - INFO - Inicio de la ejecución
2024-08-25 21:10:38,197 - uvicorn.error - INFO - Started server process [24596]
2024-08-25 21:10:38,197 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 21:10:38,198 - uvicorn.error - INFO - Application startup complete.
2024-08-25 21:11:14,400 - app_logger - INFO - Inicio de la ejecución
2024-08-25 21:11:14,449 - uvicorn.error - INFO - Started server process [11260]
2024-08-25 21:11:14,450 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 21:11:14,450 - uvicorn.error - INFO - Application startup complete.
2024-08-25 21:11:33,814 - app_logger - INFO - Inicio de la ejecución
2024-08-25 21:11:33,860 - uvicorn.error - INFO - Started server process [19216]
2024-08-25 21:11:33,860 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 21:11:33,861 - uvicorn.error - INFO - Application startup complete.
2024-08-25 21:11:37,292 - app_logger - ERROR - HTTPException: the JSON object must be str, bytes or bytearray, not list (status: {'ret_code': -1, 'ret_txt': 'the JSON object must be str, bytes or bytearray, not list'})
2024-08-25 21:13:50,068 - app_logger - INFO - Inicio de la ejecución
2024-08-25 21:13:50,114 - uvicorn.error - INFO - Started server process [12836]
2024-08-25 21:13:50,114 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 21:13:50,115 - uvicorn.error - INFO - Application startup complete.
2024-08-25 21:13:56,931 - app_logger - ERROR - HTTPException: the JSON object must be str, bytes or bytearray, not list (status: {'ret_code': -1, 'ret_txt': 'the JSON object must be str, bytes or bytearray, not list'})
2024-08-25 21:14:31,844 - app_logger - INFO - Inicio de la ejecución
2024-08-25 21:14:31,887 - uvicorn.error - INFO - Started server process [29380]
2024-08-25 21:14:31,887 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 21:14:31,888 - uvicorn.error - INFO - Application startup complete.
2024-08-25 21:16:39,294 - app_logger - INFO - Inicio de la ejecución
2024-08-25 21:16:39,858 - uvicorn.error - INFO - Started server process [19200]
2024-08-25 21:16:39,858 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 21:16:39,859 - uvicorn.error - INFO - Application startup complete.
2024-08-25 21:16:42,177 - app_logger - ERROR - HTTPException: the JSON object must be str, bytes or bytearray, not list (status: {'ret_code': -1, 'ret_txt': 'the JSON object must be str, bytes or bytearray, not list'})
2024-08-25 21:28:28,858 - app_logger - INFO - Inicio de la ejecución
2024-08-25 21:28:28,903 - uvicorn.error - INFO - Started server process [33236]
2024-08-25 21:28:28,904 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 21:28:28,904 - uvicorn.error - INFO - Application startup complete.
2024-08-25 21:29:04,917 - app_logger - INFO - Inicio de la ejecución
2024-08-25 21:29:04,962 - uvicorn.error - INFO - Started server process [9160]
2024-08-25 21:29:04,962 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 21:29:04,963 - uvicorn.error - INFO - Application startup complete.
2024-08-25 21:29:08,327 - app_logger - ERROR - HTTPException: the JSON object must be str, bytes or bytearray, not list (status: {'ret_code': -1, 'ret_txt': 'the JSON object must be str, bytes or bytearray, not list'})
2024-08-25 21:30:14,659 - app_logger - INFO - Inicio de la ejecución
2024-08-25 21:30:15,094 - uvicorn.error - INFO - Started server process [27104]
2024-08-25 21:30:15,095 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 21:30:15,096 - uvicorn.error - INFO - Application startup complete.
2024-08-25 21:30:48,558 - app_logger - INFO - Inicio de la ejecución
2024-08-25 21:30:48,610 - uvicorn.error - INFO - Started server process [16932]
2024-08-25 21:30:48,611 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 21:30:48,611 - uvicorn.error - INFO - Application startup complete.
2024-08-25 21:36:05,196 - app_logger - INFO - Inicio de la ejecución
2024-08-25 21:36:05,872 - uvicorn.error - INFO - Started server process [31268]
2024-08-25 21:36:05,872 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 21:36:05,873 - uvicorn.error - INFO - Application startup complete.
2024-08-25 21:41:43,413 - app_logger - INFO - Inicio de la ejecución
2024-08-25 21:41:43,731 - uvicorn.error - INFO - Started server process [24340]
2024-08-25 21:41:43,731 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 21:41:43,732 - uvicorn.error - INFO - Application startup complete.
2024-08-25 21:41:52,889 - app_logger - ERROR - Unhandled Exception: 'datos'
2024-08-25 21:41:52,890 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\exceptions.py", line 93, in __call__
    raise exc
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\lvicente\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Nube\GitHub\Madre_API\app\api\routes\semillas.py", line 34, in valida_url
    datos        = resultado['datos']
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'datos'
2024-08-25 21:45:27,223 - app_logger - INFO - Inicio de la ejecución
2024-08-25 21:45:27,876 - uvicorn.error - INFO - Started server process [32188]
2024-08-25 21:45:27,877 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 21:45:27,877 - uvicorn.error - INFO - Application startup complete.
2024-08-25 21:49:12,976 - app_logger - INFO - Inicio de la ejecución
2024-08-25 21:49:13,319 - uvicorn.error - INFO - Started server process [34472]
2024-08-25 21:49:13,319 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 21:49:13,320 - uvicorn.error - INFO - Application startup complete.
2024-08-25 21:53:27,071 - app_logger - INFO - Inicio de la ejecución
2024-08-25 21:53:27,585 - uvicorn.error - INFO - Started server process [34012]
2024-08-25 21:53:27,585 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 21:53:27,586 - uvicorn.error - INFO - Application startup complete.
2024-08-25 21:59:56,335 - app_logger - INFO - Inicio de la ejecución
2024-08-25 21:59:57,404 - app_logger - INFO - Inicio de la ejecución
2024-08-25 21:59:57,451 - uvicorn.error - INFO - Started server process [33868]
2024-08-25 21:59:57,452 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 21:59:57,452 - uvicorn.error - INFO - Application startup complete.
2024-08-25 22:00:01,484 - app_logger - ERROR - HTTPException: isinstance() arg 2 must be a type, a tuple of types, or a union (status: {'ret_code': -1, 'ret_txt': 'isinstance() arg 2 must be a type, a tuple of types, or a union'})
2024-08-25 22:03:10,827 - app_logger - INFO - Inicio de la ejecución
2024-08-25 22:03:11,386 - uvicorn.error - INFO - Started server process [5448]
2024-08-25 22:03:11,386 - uvicorn.error - INFO - Waiting for application startup.
2024-08-25 22:03:11,387 - uvicorn.error - INFO - Application startup complete.
2024-08-25 22:03:41,846 - uvicorn.error - INFO - Shutting down
